### PR TITLE
VR improvements

### PR DESCRIPTION
**Pull request by Sgeo**
I don't actually know what I'm doing, if this can trigger a build and/or if there is a way to get the commits in a more up-to-date branch.

### CODE REVIEW

**Comment by RoseIlanga** [comment]
Did any of these changes ever get incorporated?

**Comment by Sgeo** [comment]
https://github.com/Sgeo/firestorm-gha/commits/Firestorm_6.6.3_VR_Sgeo is marginally more up to date, but I haven't looked at this in a while, to be honest. I last left off with decent VR (although the FOV calculation is not ideal), but was stuck trying to make the UI more usable.

**Comment by Sgeo** [comment]
It's also possible I have code changes on my HD that aren't present there.

**Comment by RoseIlanga** [comment]
Oh, okay. I was mostly wondering if @humbletim had made any similar changes to this repository that made this pull request obsolete. It looks like https://github.com/humbletim/firestorm-gha/tree/Firestorm_6.6.8 has the latest changes. I'll try out both this one and yours to compare how well they work for me.

**Comment by RoseIlanga** [comment]
Hm... I can build humbletim's version, but not yours (using a custom PKGBUILD). Cmake has trouble finding OpenVR for some reason.

```
ERROR: unknown package: openvr
For more information: try re-running your command with --verbose or --debug
CMake Error at cmake/Prebuilt.cmake:57 (message):
  Failed to download or unpack prebuilt 'openvr'.  Process returned 1.
Call Stack (most recent call first):
  newview/CMakeLists.txt:68 (use_prebuilt_binary)
```

I'm on Manjaro, and I have OpenVR installed, if that helps.

**Comment by aiaustin** [comment]
Is this work still relevant to latest versions Pre-PBR 6.6.17 and trials of PBR 7.1.4 and could it offer better quality VR visuals? Humbletim is working on improved GHA action workflows that should enable easier building and trials.

**Comment by Sgeo** [comment]
> Is this work still relevant to latest versions Pre-PBR 6.6.17 and trials of PBR 7.1.4 and could it offer better quality VR visuals? Humbletim is working on improved GHA action workflows that should enable easier building and trials.

This was before my recent work on FOV improvements (fully correct FOV). My current 2024 has all the rest of this VR code, and the FOV changes.

It's possible that I'd go back to this code, but only as a last ditch effort to do something to get UI half decent.

**Comment by aiaustin** [comment]
Sgeo VR Min version now available via Releases from 7.1.11.

**Pull request closed without merging**
